# Configuración ALSA:
# Entrada (Micrófono): Integrado Laptop (DMIC hw:0,6)
# Salida (Audio/Altavoces): Audífonos JBL Quantum350 Wireless (hw:Wireless,0)

pcm.entrada_buena {
    type plug
    slave {
        pcm "hw:0,6"
    }
}

pcm.entrada_buena_16k {
    type plug
    slave {
        pcm "entrada_buena"
        rate 16000
    }
}

# Salida de audio mezclada (dmix) para los audífonos JBL
pcm.dmix_jbl {
    type dmix
    ipc_key 1024
    ipc_key_add_uid false
    ipc_perm 0666
    slave {
        pcm "hw:Wireless,0"
        rate 48000
    }
}

pcm.salida_jbl {
    type plug
    slave {
        pcm "dmix_jbl"
    }
}

# Asignar la salida JBL y la entrada Micrófono como predeterminadas del sistema
pcm.!default {
    type asym
    playback.pcm "salida_jbl"
    capture.pcm "entrada_buena"
}

pcm.!sysdefault {
    type plug
    slave.pcm "default"
}

ctl.!default {
    type hw
    card "Wireless"
}
