# Configuración ALSA:
# Entrada (Micrófono): Integrado Laptop (DMIC hw:0,6)
# Salida (Audio/Altavoces): Parlantes internos de la laptop (hw:0,0)

pcm.entrada_buena {
    type plug
    slave {
        pcm "hw:0,6"
    }
}

pcm.entrada_buena_16k {
    type plug
    slave {
        pcm "entrada_buena"
        rate 16000
    }
}

# Salida de audio mezclada (dmix) para los parlantes internos
pcm.dmix_laptop {
    type dmix
    ipc_key 1025
    ipc_key_add_uid false
    ipc_perm 0666
    slave {
        pcm "hw:0,0"
        rate 48000
    }
}

pcm.salida_laptop {
    type plug
    slave {
        pcm "dmix_laptop"
    }
}

# Salida de respaldo JBL (por si se necesita)
pcm.salida_jbl {
    type plug
    slave {
        pcm "hw:Wireless,0"
    }
}

# Asignar la salida de los parlantes y la entrada de Micrófono como predeterminadas del sistema
pcm.!default {
    type asym
    playback.pcm "salida_laptop"
    capture.pcm "entrada_buena"
}

pcm.!sysdefault {
    type plug
    slave.pcm "default"
}

ctl.!default {
    type hw
    card 0
}
